ShrianshWEB/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('products.urls')),
    path('', include('accounts.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
]

cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

orders/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
    path('history',views.order_history, name='history'),
    path('history/<id>',views.order_history_list, name='order_list')
]

products/urls.py
from django.urls import path
from .import views

app_name = 'produits'

urlpatterns = [
    path('products/',views.product_list, name='product_list'),
    path('search/', views.search, name='Search'),
    path('<category_slug>/',views.product_list, name='product_list_by_category'),
    path('<id>/<slug:slug>/',views.product_detail, name='product_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms
from products.admin import Product

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 11)]


class CartAddProductForm(forms.Form):
    
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from products.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('produits:product_list')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    template_name = 'cart/detail.html'
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, template_name, {'cart': cart})

cart/templates/cart/detail.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}
Your Shopping Cart
{% endblock %}


{% block content %}
<div class="container">
    <div class="row" style="margin-top: 6%">
        <h2>Your Shopping Cart
            <span class="badge pull-right">
                {% with totail_items=cart|length %}
                {% if cart|length > 0 %}
                My Shopping Order:
                <a href="{% url 'cart:cart_detail' %}" style="color: #ffffff">
                    {{ totail_items }} item {{ totail_items|pluralize }},  {{ cart.get_total_price }} INR
                </a>
                {% else %}
                Your cart is empty.
                {% endif %}
                {% endwith %}
            </span>
        </h2>
        <table class="table table-striped table-hover">
            <thead style="background-color: #ff3300; color:cornsilk">
                <tr>
                    <th>Image</th>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th>Remove</th>
                    <th>Unit Price</th>
                    <th>Price</th>
                </tr>
            </thead>
            <tbody>
                {% for item in cart %}
                {% with product=item.product  %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}"
                                alt="..." style="height: 130px; width: auto">
                        </a>
                    </td>
                    <td>{{ product.nameProd }}</td>
                    <td>
                        <form action="{% url "cart:cart_add" product.id %}" method="post">
                            {% csrf_token %}
                            {{ item.update_quantity_form.quantity }}
                            {{ item.update_quantity_form.update }}
                            <input type="submit" value="Update" class="btn btn-info">
                        </form>
                    </td>
                    <td>
                        <a href="{% url "cart:cart_remove" product.id %}">Remove</a>
                    </td>
                    <td>{{ item.price }} INR</td>
                    <td>{{ item.total_price }} INR</td>
                </tr>
                {% endwith %}
                {% endfor %}
                <tr style="background-color: #ff3300; color:cornsilk;">
                    <td><b>Total</b></td>
                    <td colspan="4"></td>
                    <td colspan="num"><b>{{ cart.get_total_price }} INR</b></td>
                </tr>
            </tbody>
        </table>
        <p class="text-right">
            <a href="{% url 'produits:product_list' %}" class="btn btn-default">Continue Shopping</a>
            <a href="{% url 'orders:order_create' %}" class="btn btn-primary">Checkout</a>
        </p>
    </div>
</div>
</br>
{% endblock %}