ShrianshWEB/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('products.urls')),
    path('', include('accounts.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
]

cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

orders/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
    path('history',views.order_history, name='history'),
    path('history/<id>',views.order_history_list, name='order_list')
]

orders/models.py
from django.db import models
from products.models import Product
from django.conf import settings

class Order(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'Order{}'.format(self.id)
        
    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())

class OrderItem(models.Model):

    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = []

orders/views.py
from django.shortcuts import render
from .models import OrderItem, Order
from .forms import OrderCreateForm
from cart.cart import Cart
from accounts.models import MyUser
from products.models import Product

from django.contrib.auth import get_user
from django.contrib.auth.decorators import login_required


@login_required
def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            user = MyUser.objects.get(email=request.user.email)
            order.user = user
            order.save()
            for item in cart:
                pro = Product.objects.get(nameProd=item['product'])
                pro.stock = pro.stock - item['quantity']
                pro.save()
                OrderItem.objects.create(
                    order=order,
                    product=item['product'],
                    price=item['price'],
                    quantity=item['quantity']
                )
                
            cart.clear()
        return render(request, 'orders/order/created.html', {'order': order})
    else:
        form = OrderCreateForm()
    return render(request, 'orders/order/create.html', {'form': form})


@login_required
def order_history(request):
    user = request.user
    purchases = Order.objects.filter(user_id=user.id)
    context = {
        'purchases': purchases
    }
    return render(request, 'orders/order/history.html', context)


@login_required
def order_history_list(request, id):
    template_name = 'orders/order/list.html'

    order_id = OrderItem.objects.filter(order=id)
    product = Product.objects.all()

    context = {
        'order_items': order_id,
        'product': product
    }

    return render(request, template_name, context)

orders/templates/orders/order/create.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}
Your Shopping Cart| Checkout
{% endblock %}

{% block content %}
<div class="container">
    <div class="row" style="margin-top: 6%">
        <div class="col-md-8">
            <h4 class="page-header">Checkout</h4>
            <form action="." method="post">
                {% csrf_token %}
                {{ form.as_p }}<br>
                <input type="submit" class="btn btn-primary" value="Submit order">
            </form>
        </div>
        <div class="col-md-4">
            <div class="page-header">
                Your Order
            </div>
            <ul class="list-group">
                {% for item in cart %}
                <li class="list-group-item">
                    {{ item.quantity }}x {{ item.product.name }}
                    <span>INR. {{ item.total_price }}</span>
                </li>
                {% endfor %}

                <li class="list-group-item active">Total Cost: INR. {{ cart.get_total_price }}</li>
            </ul>

        </div>
    </div>
</div>
{% endblock %}

orders/templates/orders/order/created.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}
Your Shopping Cart| Thank you
{% endblock %}

{% block content %}
<div class="container">
    <div class="row" style="margin-top: 6%">
        <div class="col-md-8 col-md-offset-2">
            <h3 class="page-header">Thank You For Shopping With Us
            </h3>
            <p>Your order has been successfully completed. Your order number is <strong>{{ order.id }}</strong>.</p>
        </div>
    </div>
</div>
{% endblock %}

orders/templates/orders/order/history.html
{% extends 'shop/base.html' %}
{% load static %}
{% block content %}
<table class="table">
    <thead>
        <tr>
        <th scope="col">ID Purchase</th>
        <th scope="col">Date of Purchase</th>
        <th scope="col">Date of Update</th>
        </tr>
    </thead>
    <tbody>
        {% for order in purchases %}
            <tr>
            <td><a href="{% url 'orders:order_list'  order.id %}">{{order.id}}</a></td>
            <td>{{order.created}}</td>
            <td>{{order.updated}}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

orders/templates/orders/order/list.html
<!-- list.html -->

{% extends 'shop/base.html' %}
{% load static %}
{% block content %}
     
          <table class="table">
    <thead>
        <tr>
        <th scope="col">Product</th>
        <th scope="col">Price</th>
        <th scope="col">Quanitity</th>
        </tr>
    </thead>
    <tbody>

        {% for items in order_items %}

            <tr>
            <td><a href="">{{items.product}}</a></td>
            <td>{{items.price}}</td>
            <td>{{items.quantity}}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}